[versions]
agp = "8.12.3"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"

# Firebase / Google - Versions
firebaseBomV="34.7.0"
googleServicesV="4.4.4"

circleImageV="3.1.0"
glideV="5.0.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Firebase / Google - Libraries
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomV" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-credentials = { module = "androidx.credentials:credentials" }
firebase-credentials-service = { module = "androidx.credentials:credentials-play-services-auth" }
firebase-identity-googleid = { module = "com.google.android.libraries.identity.googleid:googleid" }

circle-images = { module = "de.hdodenhof:circleimageview", version.ref = "circleImageV" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideV"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Google - Plugins
googleService={ id= "com.google.gms.google-services", version.ref= "googleServicesV"}